import type { Metadata } from "next";
import {fontRoboto} from "@/lib/fonts";
import AuthListener from "@/app/AuthListener";
import "./globals.css";
import AuthModal from "@/app/(public)/components/Modals/AuthModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontRoboto.variable} font-roboto`}>
      {children}
      <AuthModal />
      </body>
    </html>
  );
}
